### PR TITLE
Possibilty to add automatically rules from the FormRequest Object

### PR DESCRIPTION
**Pull request by akiyamaSM**
Add the possiblity to get the rules from the FormRequest object. for example 
`{!! Form::number("mark", null, ["class" => "form-control", "request" => "App\Http\Requests\MarkRequest"] ) !!}`

and in the MarkRequest rules 
 `['mark' => 'required|max:20']`

results : 

`<input class="form-control" name="mark" required="required" max="20" type="number">`

### CODE REVIEW

**Comment by akiyamaSM** [comment]
what about this @adamgoose?

**Comment by akiyamaSM** [comment]
Any feedback?

**Comment by parmap** [comment]
Looks nice.

 Is it possible to extend it little bit? For example, `min` and `max` functions depends on input type (min as string should be printed as minlength). And the non-valid html attributes print as data-* attribute, which we will be able to manipulate with js.

 My point is - write rules once and use twice (server and client). I will be able to create jquery plugin, which will parse these inputs attributes and create client form validation, but right now, it's not possible.

**Comment by mlantz** [comment]
Hey so from my perspective, it feels weird to have a request connected to a specific input field, when I think about requests I think in terms of checking against a payload, which is relative to an object. Just as well, the request rules are designed and defined by the Laravel framework. If anything I would be totally cool with [pattern](http://caniuse.com/#search=pattern) 

```
{!! Form::number("mark", null, ["class" => "form-control", "pattern" => "regex pattern"] ) !!}
```

The above example would be supported by most browsers and give a basic layer of validation without conflicting with the Laravel rules. Thoughts?

**Comment by akiyamaSM** [comment]
@mlantz I see, the idea was to use the Request and use it's validation rules and apply it on the fields implecitly.

**Comment by mlantz** [comment]
Yeah I get the idea to pull from the request the rules relative to the field. But like I said, I don't think it makes a lot of sense given that Laravel decides the rules and their support level for the framework, whereas the browser has very different rules which may not be available. The pattern one is the only one that has full support 'technically' even though Safari wont even display an error statement if incorrect.

**Comment by akiyamaSM** [comment]
@mlantz Yes, You are right ;)

**Comment by parmap** [comment]
Ok, but look [here](https://www.w3.org/TR/html5/forms.html#common-input-element-attributes). My point is not let browsers try to do the validation, which he don't know about. The unusual validations would be marked with `data` prefix and the input validated by js. The idea is only in linking input and request, so you won't have to repeat yourself. You define rules in request and the logic will used them in view. Of course, you should be able to turn it of for specific input, or don't use at all in form. So it's not some background magic, but improvement.

**Comment by mlantz** [comment]
I'm still not convinced about this PR given the conversation. One could implement a macro which utilized the Model's rules in order to generate a input which could be validated by some JavaScript. Thanks @akiyamaSM for putting in the PR I appreciate your patience.

**Pull request closed without merging**
