### PR TITLE
Fill values by current Request

### PR DESCRIPTION
**Pull request by decadence**
I tried to implement what I want here https://github.com/LaravelCollective/html/issues/180
Shortly: adding support for fill value from Request in case you want autosave user input without redirect. Maybe useful for filter or search pages when you can't redirect user to show result and want filter params to be saved.

### CODE REVIEW

**Comment by Decadence** [comment]
What's about considering this guys?
@tshafer
@adamgoose

**Comment by Decadence** [comment]
Bump.
Is there anybody?

**Comment by skyrpex** [comment]
Are they alive? haha

**Comment by Decadence** [comment]
Hardly

**Comment by mlantz** [comment]
Can you give me a more specific example of this? Is this still something you guys would like added?

**Comment by Decadence** [comment]
@mlantz 
For example you have posts filter (you can choose date interval, author, status and so on).
When you click Apply button, filter form is submitted and you show results to user **without** any redirect with calling `withInput` (so you don't have old values in session). Filter values are stored in $_GET parameters.
And you need to refill selected values in filter and there may be many of them. This PR considers fill input value with Request::input() value.
Other way you need call request("name") for each input:

`Form::text('name', request("name"))`
with PR:
`Form::text('name')`
Request will be checked automatically.

Maybe you want make this functionality optional.
Something like `Form::considerRequest()` method.

**Comment by decadence** [comment]
@mlantz any updates?

**Comment by mlantz** [comment]
Will review this weekend @decadence

**Comment by decadence** [comment]
Thanks!

**Comment by decadence** [comment]
@mlantz How do you handle new features in old versions with Git? This PR is only available for 5.2? Is there any chance to have it in current branch?

**Comment by mlantz** [comment]
Yup

I have spent the morning + afternoon crawling through any updates to 5.1, 5.2, 5.3, 5.4 and making sure any thing from 5.1+ has moved up into 5.4 and fixed the escaping issue still living in 5.3 and ensured that all tests are passing in all branches.

**Comment by decadence** [comment]
Thank you for your work

**Pull request merged**
