### PR TITLE
Updated laravel dependencies

### PR DESCRIPTION
**Pull request by morrelinko**
Updated laravel dependencies to include 5.1 support

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by GrahamCampbell** [comment]
`~5.0` DOES allow 5.1...

**Comment by adamgoose** [comment]
The 5.1 deps can be installed by installing ~5.1@dev until we have time to solidify stability.

**Comment by GrahamCampbell** [comment]
@adamgoose That's not true. Your 5.0 branch allows 5.1 installs...

**Comment by GrahamCampbell** [comment]
`~5.0` means `5.x`...

**Comment by adamgoose** [comment]
Yeah, you're right. I'll update to 5.0.* and 5.1.* before we tag 5.1 versions.

**Comment by morrelinko** [comment]
@GrahamCampbell Yea!

**Comment by GrahamCampbell** [comment]
Updating the 5.0 branch is a waste of time, because you've already made the mess. Now if someone has L5.3, composer will just go and find an old 5.0.x tag on this repo because you marked it as compatible...

**Comment by kaidesu** [comment]
Just for clarification, I've made this same mistake with Composer and Laravel - Laravel does not follow semantic versioning; Laravel 5.1 is what would be a 6.0 release.

When referencing dependencies in Composer, the tilde (`~`) and caret (`^`) operators are for projects that follow semantic versioning (https://getcomposer.org/doc/01-basic-usage.md#package-versions).

This is why Laravel itself lists the framework dependency as `5.1.*` and not `~5.1`.

**Comment by JosephSilber** [comment]
The correct way to reference Laravel is ^5.1.0.

**Comment by JosephSilber** [comment]
To support 5.0 and 5.1, use ^5.0.0|^5.1.0.

**Comment by GrahamCampbell** [comment]
@JosephSilber No, you're wrong. You want `~` NOT `^`.

**Comment by GrahamCampbell** [comment]
Best way is `5.0.*|5.1.*`.

**Pull request closed without merging**
