### PR TITLE
Updated installation documentation: Composer installation in one step

### PR DESCRIPTION
**Pull request by FR6**

### CODE REVIEW

**Comment by JosephSilber** [comment]
Why specify a version at all?

   composer require laravelcollective/html

**Comment by adamgoose** [comment]
Sorry, but no thanks.

**Comment by JosephSilber** [comment]
@adamgoose may I ask why?

**Comment by adamgoose** [comment]
I prefer the `composer.json` way personally, and I'm trying to match the attitude of the Laravel documentation, which recommends this way as well.

https://github.com/laravel/docs/blob/5.0/billing.md

**Pull request closed without merging**
