### PR TITLE
Laravel 11.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 11.x.

**Before merging**, you need to:

- Checkout the `l11-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: The latest version of Laravel has a dependency for `phpunit/phpunit` of `^10.5`. If you would like to also upgrade your tests, you may run the [PHPUnit 10 Shift](https://laravelshift.com/upgrade-phpunit-10) for free.

**Comment by laravel-shift** [comment]
:information_source: Shift detected you do not have a CI workflow using GitHub Actions. If you would like, Shift can help you get started with the [CI Generator](https://laravelshift.com/ci-generator). Although the Shift is paid, GitHub Actions is free and having a CI workflow will improve the stability and review process for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/html.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "laravelcollective/html": "dev-l11-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by aglipanci** [comment]
@mlantz I would appreciate if you could find the time to merge this PR. It's rather a small change so there isn't much to review.

Thanks in advance!

**Comment by kj-wielink** [comment]
Meanwhile fork https://github.com/gridplay/gphtml has already support for Laravel 11

**Comment by aglipanci** [comment]
@kj-wielink thanks! I already moved to spatie-html package, I just hoped for a quick merge.

**Comment by kossa** [comment]
Please merge this PR

**Comment by Chrisx84** [comment]
> Meanwhile fork https://github.com/gridplay/gphtml has already support for Laravel 11

thanks for the shout out eh :)

**Comment by vedmant** [comment]
Just curios why you do like `"illuminate/http": "^6.0|^7.0|^8.0|^9.0|^10.0",` when `"illuminate/http": ">=6.0",` will work for any new version without need to add it?

**Comment by laravel-shift** [comment]
This package is abandoned.

**Comment by Chrisx84** [comment]
> This package is abandoned.

thats why we developers forked our own like me.
gridplay/gphtml

**Pull request closed without merging**
