### PR TITLE
search for translation to show the label text

### PR DESCRIPTION
**Pull request by jorgevilaca82**

### CODE REVIEW

**Comment by mlantz** [comment]
Would it not be better to do something similar to: `Form::label(Lang::get('name'))` rather than expect the label to translate for you? It feels weird to have the label assume that you may want a translation

**Comment by mlantz** [comment]
Have you considered my previous comment?

**Comment by jorgevilaca82** [comment]
The idea is just a shortcut helper, but yeah, you're right!
Sorry for the late answer!

**Comment by jorgevilaca82** [comment]
It is the rails way! ;)

**Pull request closed without merging**
