### PR TITLE
Create datalist form element

### PR DESCRIPTION
**Pull request by joseraul**
Ways to use:
```
Form::datalist('genders', ['M' => 'Male', 'F' => 'Female']);
...
<datalist id="genders">
  <option value="M">Male</option>
  <option value="F">Female</option>
</datalist>
```
```
Form::datalist('genders', [5 => 'Male', 6 => 'Female']);
...
<datalist id="genders">
  <option value="5">Male</option>
  <option value="6">Female</option>
</datalist>
```
```
Form::datalist('genders', ['Male', 'Female']);
...
<datalist id="genders">
  <option value="Male">Male</option>
  <option value="Female">Female</option>
</datalist>
```

### CODE REVIEW

**Comment by djh101** [comment]
No support for attributes?

**Comment by djh101** [comment]
Also, I wonder if perhaps the key and value should be switched so that the key is used as the label (the inner html if the value attribute is present) and the value as the value? On that note, is there a convention for which to use between the label attribute, the value attribute, and the inner html? Only two are needed as the inner html will act as either the label or the value, whichever is absent (or the value if neither are present).

**Comment by joseraul** [comment]
Hi @djh101 ! Nice to see you! Sorry to have pushed a task that you were working on, but I needed the functionality and you look disappeared for months...

- About the attributes, in theory, the element datalist is hidden by the browser, so I decided to not support it. I don't know if some users will be interested in adding something like data-foo or something like that.. what do you think?
- About the key => value. For me, this is the order that makes more sense and developers are used to it. Anyway, every browser represents it in different ways. I would let the developers the decision to switch or not the array.

**Comment by djh101** [comment]
That's fine with me, I was just curious what the rationale was (and Tom Shafer seemed to have gone away and pull requests were piling up, it seemed like this repository had been abandoned).

To the first point, I can't imagine many (if any) scenarios where one might want to add attributes to datalists or their options, I just have a habit of keeping things as general as possible. Maybe for some reason someone would rather use the label attribute to set option labels than the innerhtml value or they want to give the datalist options ids? Though I do recall a certain coding rule about waiting until you actually need a feature before adding it, so I suppose there's no harm in leaving it how it is until someone comes forward needing to add attributes to their datalist.

To the second point, I suppose that the current way does seem a little more natural, it just sounds a little confusing when put into words (the key gives the value and the value gives the label), but otherwise I don't really have a strong opinion either way. I'll double check in the morning, but I think we wouldn't need the associative checking function if it were reversed?

**Pull request merged**
