### PR TITLE
added nbsp() to generate repeated &nbsp tag

### PR DESCRIPTION
**Pull request by rajatsharma94**

### CODE REVIEW

**Comment by mlantz** [comment]
Where and why do you need to do nbsp? or a number of them. It seems kinda weird to encourage the use of those.

**Comment by rajatsharma94** [comment]
Most of the frameworks support it, and its a valid html character entity. Thought it would do no harm in adding some support.

**Comment by mlantz** [comment]
Can you fix the styleci? And then I'm happy to merge it in. Thanks.

**Comment by rajatsharma94** [comment]
@mlantz, fixed that, just had to merge again. I guess there was some problem with my previous editor.

**Comment by rajatsharma94** [comment]
@mlantz, Fixed it.

**Pull request merged**
