### PR TITLE
[5.4] Html escaping is now optional for buttons

### PR DESCRIPTION
**Pull request by StefanPrintezis**
Since buttons are able to contain html i've made escaping optional.

#205

### CODE REVIEW

**Comment by garygreen** [comment]
This is just getting ridiculous adding these "non escaping" stuff to nearly everything imo. Laravel's `e()` has a pretty neat feature in that you can supply it with a `HtmlString` safe object, couldn't we make use of that instead?

**Comment by tshafer** [comment]
I don't like boolean variables in functions.

**Comment by StefanPrintezis** [comment]
@tshafer So how would you solve this then? HTML in buttons is pretty common.

**Comment by garygreen** [comment]
Must every form element be coded with the package. Buttons, really? With that said, can we get a PR to add Form::div() already please, I'm gagging for that. 😋

**Pull request closed without merging**
