### PR TITLE
Fix select for old input

### PR DESCRIPTION
**Pull request by Vendin**

### CODE REVIEW

**Comment by lk77** [comment]
Hello,

we need a fix for this problem,
we are now forced to cast to int since commit f620ae4 (May 20), which is not elegant.
this PR needs to be merged.

thanks

**Comment by perskinet** [comment]
It's also important for me :)

**Comment by dtbarne** [comment]
We forked and removed the strict check in the meantime.

**Comment by noel45** [comment]
Maybe I get it wrong but I think the proposed change only fixes 1 side of the issue : 

`return in_array($value, $selected, true) || in_array((string) $value, $selected, true)`

What if the problems arise from "$selected" being an integer ? Then the problem will still happen. The definitive solution would be to remove the strict check in the in_array function

Especially passing the list keys as integer is useless because when the value is retrieved from the "old" function it is then converted to a string !

**Comment by lk77** [comment]
this PR was fixed as said by @dtbarne

**Comment by mikeher** [comment]
Make us all happy - merge this PR! :-*

**Comment by Artistan** [comment]
please merge, the only "failed" check is hhvm issue, not code issue....

**Comment by Braunson** [comment]
Any idea when this will be merged? It's a critical fix for many of of.

**Comment by Dartui** [comment]
@Braunson this is merged, but not yet released. You could use 5.4 branch in your composer to get this update

**Comment by Braunson** [comment]
@Dartui Thanks, any ETA on when this will be released?

**Comment by MatheusNaldi** [comment]
It was not merged to 5.3 version, please fix this

**Pull request merged**
