### PR TITLE
Fix for undefined function getToken() on Laravel 5.5

### PR DESCRIPTION
**Pull request by billmn**

### CODE REVIEW

**Comment by decadence** [comment]
https://github.com/LaravelCollective/html/pull/372

**Comment by tomswinkels** [comment]
When will this issue merged to a new version?

**Comment by RyanThompson** [comment]
Why has this not been merged yet? Seems obvious to accept, no?

**Comment by RyanThompson** [comment]
This is the only thing standing between me and an installable / 100% working version of https://github.com/pyrocms/pyrocms on L55 - halp meh!

**Comment by ajaaibu** [comment]
When is this going to be merged?

**Comment by decadence** [comment]
@mlantz ping

**Pull request closed without merging**
