### PR TITLE
changed select placeholder to reflect major browser standards

### PR DESCRIPTION
**Pull request by darthrevan13**
http://stackoverflow.com/a/8442831/1722248

### CODE REVIEW

**Comment by mlantz** [comment]
Please ensure your code passes all checks.

**Comment by yaykyle** [comment]
Funny I was just coming to see if anyone had requested this! Nice work.

**Comment by darthrevan13** [comment]
I updated all affected test cases.

**Comment by sebdesign** [comment]
This is a breaking change! Please see #347.

**Pull request merged**
