### PR TITLE
[5.1] Checkboxes work with relationships

### PR DESCRIPTION
**Pull request by alexandre-butynski**
This commits has been merged into 5.0 (thanks for that) but should also be merged into 5.1.

As @arthurkirkosa said in #45, a new release would be great.

### CODE REVIEW

**Comment by alexandre-butynski** [comment]
@adamgoose this should also be merged into master (just a fast forward).

In general, I think that all fixes or improvements in old branches should be merged into master when it's possible. I see two commits of @rumeau that should be merged into master too.

Thanks in advance.

**Comment by arthurkirkosa** [comment]
@adamgoose ping

**Comment by arthurkirkosa** [comment]
It's getting ridiculous with this pull request.

**Comment by alexandre-butynski** [comment]
You're right. I have made this pull request initially on June 1st (https://github.com/LaravelCollective/html/pull/45) and, 3 months after, it is still not merged into the latest branch...

:confused: 

This is not something really complex and it is an answer to a real issue in this package, several issues were posted about that. This situation is quite scary about the future of the package and does not encourage contributions.

**Comment by alexandre-butynski** [comment]
@adamgoose, thanks ! Don't forget to merge it into the master branch too. It should just be a fast-forward.

**Pull request merged**
