### PR TITLE
[5.4] Replaced htmlentites() with htmlspecialchars()

### PR DESCRIPTION
**Pull request by StefanPrintezis**
As stated in #265 
I didn't change the name of the function, because it still creates html entities.

### CODE REVIEW

**Comment by garygreen** [comment]
What about things that shouldn't be escaped? At the moment there is no way to unescape `->select()` options, for example.

**Comment by StefanPrintezis** [comment]
@garygreen I'm sorry, but your comment doesn't feel related to this pr.

**Comment by garygreen** [comment]
Ah yeah sorry thought this was to do with form stuff

**Comment by mlantz** [comment]
Can you update the conflicts in this - there were changes done to correct a merge which should not have gone through originally.

**Pull request merged**
