### PR TITLE
[5.2] Use toArray() for Model Object Value instead of Model attributes cast

### PR DESCRIPTION
**Pull request by dennisoderwald**

### CODE REVIEW

**Comment by dennisoderwald** [comment]
Ping. :)

**Comment by adamgoose** [comment]
Dennis -

Can you write a test or explain the issue you're having with the way the code now?? I'm not sure what this is offering.

Thanks,
Adam.

**Comment by dennisoderwald** [comment]
@adamgoose: This allows you to use reserved names for properties as well and prevents errors in case you do wish to use it (e.g. when using "attributes" in forms).

**Comment by arcanedev-maroc** [comment]
Hi @dennisoderwald,

The tests are failing, [Check your PR on Travis CI](https://travis-ci.org/LaravelCollective/html/builds/99192905).

**Comment by adamgoose** [comment]
Dennis - just so so you know, I've reverted your PR. Let's talk on Slack today to find out what we can do for you.

**Pull request merged**
