### PR TITLE
Supports blade directives

### PR DESCRIPTION
**Pull request by mlantz**
Creates a collection of blade directives for available html, and form methods.

### CODE REVIEW

**Comment by anatoliyarkhipov** [comment]
It's a really cool feature. Could you please show some examples, how you assume they should be used?

**Comment by garygreen** [comment]
This seems OTT imo. I think it should be down to the user to define the most used form functions and add blade directive helpers in their own app if they like.

**Comment by mlantz** [comment]
Just seemed pretty handy in my mind. A couple examples would look like:

```
@form_open()
@form_token()
@form_label()
@form_ checkbox()
@form_close()

@html_ style()
@html_favicon()
```

It's been a while I'd have to fix the PR it wont work with Laravel 5.3 right now.

**Comment by lukasoppermann** [comment]
This would be awesome, any chance this will be merged?

**Comment by mlantz** [comment]
Ah great question, I'll update and merge today sorry for the delays

**Comment by garygreen** [comment]
@mlantz what sort of impact does this have on performance? I personally won't use most, or any of these directives. Looking at the provider these directives will get added every single request, even if you won't be using the view.

**Comment by lukasoppermann** [comment]
@mlantz this is correct.

Alternatively you could maybe make the list of directives customisable in the config? I am not sure if this has a big impact in performance, but if you do not use directives you could just set the array to empty `[]` if you only need the **open** and **close** one you could set it to `['open','close']`.

**Comment by mlantz** [comment]
Closing this to update it and put it into 5.4

**Pull request closed without merging**
