### PR TITLE
Added error messages from Validator

### PR DESCRIPTION
**Pull request by andrey-helldar**
Added error messages from Validator.
Also added function a "group()".

### CODE REVIEW

**Comment by arcanedev-maroc** [comment]
it's gonna work only for twitter bootstrap v3.

**Comment by andrey-helldar** [comment]
Use the template parameter "template":

```
    /**
     * Create the block elements, including label and field
     * 
     * @param string $type
     * @param string $name
     * @param string $title
     * @param string $value
     * @param array $optionsLabel
     * @param array $optionsType
     * @param array $errors
     * @param string $selected For a Select
     * @param string $template
     * @return string
     */
    public function group($type, $name, $title, $value = null, $optionsLabel = [], $optionsType = [], $errors = null, $selected = null, $template = null)
    {
        if (is_null($template)) {
            $template = "<div class=\"form-group\">%s<div class=\"col-md-8\">%s</div></div>";
        }
	 /// ...
	}
```

**Comment by arcanedev-maroc** [comment]
How about these :
https://github.com/andrey-helldar/html/commit/93de3373553ea63acbca2a95afcfa0d90ea88ecc#diff-36caabaf080d6afdac600a28bfcd238bR321
https://github.com/andrey-helldar/html/commit/93de3373553ea63acbca2a95afcfa0d90ea88ecc#diff-36caabaf080d6afdac600a28bfcd238bR560
https://github.com/andrey-helldar/html/commit/93de3373553ea63acbca2a95afcfa0d90ea88ecc#diff-36caabaf080d6afdac600a28bfcd238bR660

**Comment by andrey-helldar** [comment]
You do not like prescribed css?

**Comment by arcanedev-maroc** [comment]
It's coupled with twitter bootstrap and nobody gonna like this.

You're forcing us to use TWB instead of Foundation, materializecss or custom css.

**Comment by andrey-helldar** [comment]
You're right. Changed principle of its modification:

	public function group($type, $name, $title, $value = null, $optionsLabel = [], $optionsType = [], $errors = null, $selected = null, $template = null) {}

The variable "$ template" can take two values: a string or array.
If you pass a string, the classes are automatically assigned from Twitter Bootstrap.
To submit your styles, you need to use an array:

	[
		'group'   => '<div class="form-group">%s<div class="col-md-8">%s</div></div>',
		'element' => 'has-error'
	]

Here, the key "element" of the array need to pass the class name of your CSS.

**Comment by andrey-helldar** [comment]
When you call the function directly, you must pass it the class name of your CSS.

Example:

	{{ Form::email('fieldId', 'value@test.com', [], $errors, 'has-error') }}

**Comment by adamgoose** [comment]
Sorry, but we do not believe that this package should have any opinion on the front-end framework being used. Thus, we don't want to support Bootstrap directly. We may have something in the pipeline!

**Comment by andrey-helldar** [comment]
I changed the code, and it is not tied to the bootstrap.
For example:
{{Form :: email ('fieldId', 'value@test.com', [], $ errors, 'has-error')}}

where instead of "has-error" can specify another class, indicating the field in error.

If you do not pass the class, then only in this case will be used by the class of the bootstrap.

**Comment by adamgoose** [comment]
Sorry, but we do not want to change the method signatures to add this functionality. Like I said, we've got something on the way that will allow you to do this per-project (which is ideal, since many projects all use different DOM syntaxes for their UI).

**Pull request closed without merging**
