### PR TITLE
Add support for Laravel 5.7

### LINKED ISSUE #564: Please open for Laravel 5.7.
We need to wait till there is a 5.7 version of laravelcollective/html because the current latest is locked to 5.6.

### PR DESCRIPTION
**Pull request by yajra**
Fix #564, #565

### CODE REVIEW

**Comment by sangnguyenplus** [comment]
Your PR looks good and it will not break anything but I don't know why the author still not merge it :|

**Comment by n-osennij** [comment]
@sangnguyenplus author (https://github.com/adamgoose) have not any activity since may

**Comment by sangnguyenplus** [comment]
@n-osennij it's not a good news :(

**Comment by vkn999** [comment]
I send mail to Adam, but got no response.

**Pull request merged**
