### PR TITLE
Update composer.json FOR L5.5

### PR DESCRIPTION
**Pull request by leyluj**
:)

Updated composer's laravel version for L5.5

### CODE REVIEW

**Comment by decadence** [comment]
You can't do it in 5.4 branch. People will be unable to use this with Laravel 5.4 then.

**Comment by leyluj** [comment]
Oh i'm new to this.

So, should i do it on master? or can you map it to a fresh 5.5 branch?

Thanks,

**Comment by decadence** [comment]
I don't know actually. You should ping @mlantz

**Comment by mlantz** [comment]
You will need to make a PR to the branch you want to merge your code into. In this case you'd aim for master @leyluj Thanks

**Pull request closed without merging**
