### PR TITLE
Fix model form-binding with array with objects and object with arrays.

### PR DESCRIPTION
**Pull request by garygreen**
This also fixes model-form binding with collections inside models.

### CODE REVIEW

**Comment by garygreen** [comment]
@tshafer what's your thoughts on this? :)

**Comment by tshafer** [comment]
I like it, I would like @adamgoose to take a look as well. I will have him take a look when he jumps online.

**Comment by tshafer** [comment]
Not sure why I didn't think to check the docs to see exactly what `data_get` does at first but it looks good to me.

**Comment by inkvizytor** [comment]
This change breaks the old behaviour for checkboxes. Check test below:
```php
$this->formBuilder->model((object)['letters' => ['b']]);
$input = $this->formBuilder->checkbox('letters[0]', 'a');
$this->assertEquals('<input name="letters[0]" type="checkbox" value="a">', $input);
```

**Comment by garygreen** [comment]
It technically 'breaks' the old behavior if you expected the BUG in your app. To me, your example is incorrect it should have checked that box because of the truthy-model binding. This isn't just a fix for checkboxes but for all things where there is a mixture of object/arrays.

**Pull request merged**
