### PR TITLE
Slightly improve Form::oldInputIsEmpty()

### PR DESCRIPTION
**Pull request by miclf**
Just a micro optimization.

This change makes the code use a native method that is returning the Boolean value it wants instead of calculating it by itself.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Tests broken.

**Comment by miclf** [comment]
Indeed.

An issue with Mockery. Didn’t see there were dependencies that needed to be mocked here. I will fix this later.

**Comment by adamgoose** [comment]
@miclf I'm reviewing PRs tomorrow. Could you either fix the tests or close the issue?

**Comment by miclf** [comment]
Closing. Sorry, I really don’t have time these days.

**Pull request closed without merging**
