### PR TITLE
Update FormBuilder.php

### PR DESCRIPTION
**Pull request by laraturka**

### CODE REVIEW

**Comment by laraturka** [comment]
Sometimes we don't want to re-populate post data for default value. It can be accepted if selected value is null.

**Comment by djh101** [comment]
How forms typically behave is when you submit the form, should you be redirected back to the form (e.g. in the case of validation errors), the form is repopulated with your input. Only if no input was given are the default values used. This is how all other form elements behave by default, and hence how select should behave as well.

See also #371.

**Comment by laraturka** [comment]
Nope. It's bit different. 
example view:
`
{!! Form::open(['url' => 'foo/bar']) !!}   
{!! Form::text('textfield', "my default value"); !!}
{!! Form::close() !!}
`
php artisan serve

http://127.0.0.1:8000/
the result is:
`
<form method="POST" action="http://127.0.0.1:8000/foo/bar" accept-charset="UTF-8"><input name="_token" type="hidden" value="XsXVaR5hwOyGFSCGI8HVoyMTQC9Bhm0E1QwPoNLq">
    
<input name="textfield" type="text" value="my default value">

</form>
`
So when i request this: http://127.0.0.1:8000/?textfield=blabla

`
<form method="POST" action="http://127.0.0.1:8000/foo/bar" accept-charset="UTF-8"><input name="_token" type="hidden" value="XsXVaR5hwOyGFSCGI8HVoyMTQC9Bhm0E1QwPoNLq">
    
<input name="textfield" type="text" value="blabla">

</form>
`
Value changes by url.

I think that it can acceptable only when default value is null.

**Comment by gekkedev** [comment]
why would someone need to use URLs like ```http://127.0.0.1:8000/?textfield=blabla```?
BTW this repository seems to not get maintained anymore 😞

**Comment by tshafer** [comment]
Please provide a test.

**Pull request closed without merging**
