### PR TITLE
Values are now encoded consistently by the formbuilder and the htmlbuilder

### PR DESCRIPTION
**Pull request by StefanPrintezis**
I've replaced e with htmlentities().
#254 Reported this as an issue.

### CODE REVIEW

**Comment by vlakoff** [comment]
In the tests, I got a bit confused by the `&nbsp;` in the select options, as they are not useful there, before I understand these `&nbsp;` are only for testing purposes.

Maybe less ambiguous test samples could be figured out ?

**Comment by vlakoff** [comment]
Thanks :)

Another suggestion, for a prettier code maybe we should use a method. Something like:
```php
// before
htmlentities($value, ENT_QUOTES, 'UTF-8')
// after
$this->escape($value)
```

**Comment by StefanPrintezis** [comment]
If the maintainers are willing to add that i'd be glad to use it, but I think that would be a new issue.

**Comment by rudiedirkx** [comment]
I agree with the new method. `htmlentities($value, ENT_QUOTES, 'UTF-8')` is logic we shouldn't repeat 8 times. But maybe `escape` is too ambigious, because `e()` escapes too. Maybe `trueEscape` or `trueEncode` or something?

**Comment by vlakoff** [comment]
I'd suggest `encodeAll`.

**Comment by StefanPrintezis** [comment]
htmlentities($value, ENT_QUOTES, 'UTF-8') is used on more rows than this patch, so i'd suggest the maintainers add a method that works for each one.

**Comment by vlakoff** [comment]
> htmlentities($value, ENT_QUOTES, 'UTF-8') is used on more rows than this patch, so i'd suggest the maintainers add a method that works for each one.

I don't understand?

**Comment by rudiedirkx** [comment]
I can find only 1 instance of `htmlentities`, which is wrong: `entities()`: https://github.com/LaravelCollective/html/search?utf8=%E2%9C%93&q=htmlentities So we need another method like `entities()` but with the correct last argument.

**Comment by vlakoff** [comment]
Agree. Keep method `entities()` as it is, for people using `HTML::entities()` in their code. Add a new method with the changed argument and use it everywhere applicable.

**Comment by StefanPrintezis** [comment]
I've added the function escapeAll() to the html builder. The form builder also uses the HTML builder to convert it's strings.

**Comment by rudiedirkx** [comment]
Anyone home?

**Comment by vlakoff** [comment]
Looks pretty good now.

I just hope there are not too many people relying (erroneously) on the "prevent double encode" parameter. Nevertheless they should fix their code, but if ever comes a flood of "issues" we can still add some "legacy" setting to the class later. But I'm a bit overcautious here.

**Comment by StefanPrintezis** [comment]
@mlantz Could you take a look?

**Comment by garygreen** [comment]
This is a MASSIVE breaking change and should not have been merged. It's caused a lot of problems for my app for characters that are now encoded but shouldn't be. For instance, we use css stars character code #9733 -- before this update they rendered fine, now they are escaped.

**Comment by garygreen** [comment]
@adamgoose @tshafer could you take a look at this one? It breaks the way 5.3 handled escaping stuff and should not have been a patch update.

**Comment by vlakoff** [comment]
Yeah, as I wrote above:

> I just hope there are not too many people relying (erroneously) on the "prevent double encode" parameter. Nevertheless they should fix their code, but if ever comes a flood of "issues" we can still add some "legacy" setting to the class later. But I'm a bit overcautious here.

I wasn't overcautious.

The change introduced in this PR is good and shouldn't be reverted. The proper way of managing this is to implement a "legacy mode", and advice developers to fix their code so they don't rely on the "prevent double encode" mechanism.

**Comment by garygreen** [comment]
What about UTF8 encoded characters? Some people may want those to appear in e.g. select options http://www.w3schools.com/charsets/ref_utf_punctuation.asp

Currently, with this PR, there's no way to output them. They always get escaped.

I agree the change introduced in this PR is good, but aspects of it have been overlooked.

**Pull request merged**
