### PR TITLE
Proposal: add a dl method to HtmlBuilder

### PR DESCRIPTION
**Pull request by devinfd**
Method generates a description list of items.

### CODE REVIEW

**Comment by devinfd** [comment]
PS: thanks for maintaining the html/form classes and keeping them alive

**Comment by adamgoose** [comment]
Can you please use tabs instead of spaces?

**Comment by devinfd** [comment]
ok

**Comment by devinfd** [comment]
Thanks for merging this in. However now that I am looking at it I see that the attributes argument uses [] as the default array as apposed to array() like everything else. Perhaps that should be changed for consistency?

**Comment by JosephSilber** [comment]
@devinfd since this package requires 5.4, everything else should be changed to `[]`, like L5.

Speaking of consistency, why is the test file indented with spaces?

**Comment by devinfd** [comment]
Your right about the 5.4 thing. I forgot about that. As for the test file I would have preferred tabs but I was trying to keep the tests consistent with the form builder test file. Personally I would like to make them both tabs and add more tests to the html builder test file but I didn't want to bumbard you with changes.

**Pull request merged**
