### PR TITLE
Use stable laravel 5.5 version

### PR DESCRIPTION
**Pull request by cmizzi**

### CODE REVIEW

**Comment by gofish543** [comment]
Release this please!!!

**Comment by aios** [comment]
What branch i must use to implement that in 5.5?

**Comment by gofish543** [comment]
I would strongly advice using the fork that cmizzi so kindly put together.
Inside your composer.json file do the following...
```
 "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/cmizzi/html"
    }
  ],
"require": {
    "laravelcollective/html": "dev-master"
  },
```
This will give you the full working library with laravel 5 until these guys get this through.

**Comment by lloricode** [comment]
output from @gofish543 , Thanks :)

screenshot from 2017-08-31 13-33-49

**Comment by lloricode** [comment]
its been 24 hours, and im ready for party :)

**Comment by goyote** [comment]
Can someone merge this

**Comment by balping** [comment]
Merge hurrah!

Just a little bit of stats until the release:


| Version | Laravel release  | LaravelCollective release |   Delay   |
| ------- | ---------------- | ------------------------- | --------- |
|     5.0 | 2015-02-04 14:17 | 2015-02-05 16:40          | 1.10 days |
|     5.1 | 2015-06-09 12:48 | 2015-06-18 02:13          | 8.56 days |
|     5.2 | 2015-12-21 17:26 | 2015-12-23 07:46          | 1.60 days |
|     5.3 | 2016-08-23 13:14 | 2016-08-27 23:52          | 4.44 days |
|     5.4 | 2017-01-24 16:19 | 2017-01-26 18:58          | 2.11 days |

(Times in UTC)

Average delay: (3.56 ± 3.07) days

Without 5.0 (this is when Laravel Collective's HTML was extracted from standard Laravel): (4.18 ± 3.17) days

**Comment by rmrhz** [comment]
Sankyu

**Comment by balping** [comment]
Updated version of my previous table:

| Version | Laravel release  | LaravelCollective release |   Delay   |
| ------- | ---------------- | ------------------------- | --------- |
|     5.0 | 2015-02-04 14:17 | 2015-02-05 16:40          | 1.10 days |
|     5.1 | 2015-06-09 12:48 | 2015-06-18 02:13          | 8.56 days |
|     5.2 | 2015-12-21 17:26 | 2015-12-23 07:46          | 1.60 days |
|     5.3 | 2016-08-23 13:14 | 2016-08-27 23:52          | 4.44 days |
|     5.4 | 2017-01-24 16:19 | 2017-01-26 18:58          | 2.11 days |
|     5.5 | 2017-08-30 09:55 | 2017-08-31 14:34          | 1.19 days |

Average delay: (3.17 ± 2.91) days

Bravo for making this release below the previous average and being the fastest if not counting 5.0!

**Comment by ElioMS** [comment]
If i use `"laravelcollective/html": "^5.5.0", ` it will works?

**Comment by lloricode** [comment]
@ElioMS, It will work now.
:)

**Comment by mahbubkhan88** [comment]
open your composer and copy paste this link composer require "laravelcollective/html":"5.4.0". That means remove "^" symbol. It will use current version. Then, composer update

**Comment by Saibamen** [comment]
@mahbubkhan88 lol, that was almost one year ago

**Pull request merged**
