### PR TITLE
Pull request for Larvel 5.8

### PR DESCRIPTION
**Pull request by ranabd36**
Remvoe Laravel deprecated helper function and use Arr and Str Facade instead. 
Update composer.json for Laravel 5.8

### CODE REVIEW

**Comment by Katenkka** [comment]
Fixes #587 

But there was PR #588 already, however this one removes deprecated helper functions, so I vote for this one

**Comment by BassemN** [comment]
:+1: Please merge

**Comment by aaronhuisinga** [comment]
This is definitely the one that should be merged. I ran this locally with 5.8 and had no issues.

**Comment by BassemN** [comment]
I hope @LaravelCollective adds more authors to approve PRs fastly as this issue happened before when Laravel 5.7 laravel released

**Comment by RalphMRivera** [comment]
> This is definitely the one that should be merged. I ran this locally with 5.8 and had no issues.

How did you get it locally? Via Composer?

**Comment by scrubmx** [comment]
@RalphMRivera 

> How did you get it locally? Via Composer?

I believe something like this in your `composer.json` will do the trick though I haven't tested it myself

```json
{
    "require": {
        "ranabd36/html": "dev-dev-5.8",
	},
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/ranabd36/html"
        }
    ],
}
```

**Comment by RalphMRivera** [comment]
Here's what worked for me:
`"repositories"`
```
    {
      "type": "git",
      "url": "https://github.com/ranabd36/html.git"
    }
```
`"require"`
```
    "laravelcollective/html": "dev-dev-5.8",
```

*Note:* The original package must be required instead of the fork.

**Comment by LeRoyJulian** [comment]
The main developer is no longer developing... He's playing music now... We should fork this repository and move on, LaravelCollective is dead.

**Comment by dwightwatson** [comment]
It's a shame - would be great if they would consider adding more collaborators to help keep it alive.

**Comment by DariusIII** [comment]
Why was this PR closed and branch deleted?

**Comment by RalphMRivera** [comment]
@DariusIII 

> Why was this PR closed and branch deleted?

It looks like it was moved here: https://github.com/ranabd36/laravelcollective

**Comment by ranabd36** [comment]
Because their inactivity. I decided to upload my forked repo into
packagist.

**Comment by DariusIII** [comment]
Ok. Thank you for your responses.

**Comment by ranabd36** [comment]
If you want then you can download it by running bellow composer command.
And let me know if you face any problem.

composer require ranabd36/laravelcollective

Thank you

**Comment by DariusIII** [comment]
Oh, i already forked and made changes in my own fork, i was just waiting
for your fix to be merged to switch back.

**Comment by ranabd36** [comment]
No problem :)

**Comment by DariusIII** [comment]
Thank you anyway :)

**Comment by aaronhuisinga** [comment]
@ranabd36 You should really re-open or create a clone PR of this. @mlantz posted on Twitter that he was on his honeymoon earlier this week (congrats, by the way!) and is working to get all of the Laravel Collective packages updated for 5.8.

**Comment by ranabd36** [comment]
Reopen Pull request

**Comment by taudau1** [comment]
Hey guys, I am pretty new to this laravel and github thing, what exact changes I need to do in my project for this work?

**Pull request merged**
