### PR TITLE
Use array_get's third parameter for default value.

### PR DESCRIPTION
**Pull request by mikemand**
This allows for using boolean values as default options for components.

### CODE REVIEW

**Comment by adamgoose** [comment]
Does this implicate you at all, or is it just cleanup? i.e. do you need me to tag this?

**Comment by mikemand** [comment]
Yes, I have a couple of components that require a boolean option (for example, if the component should render a second "confirmation" element) that are not working correctly. If you could tag this, that would be great. :smiley:

**Comment by adamgoose** [comment]
You go tit!

**Comment by mikemand** [comment]
Thank you!

**Pull request merged**
