### PR TITLE
5.4 master fixes

### PR DESCRIPTION
**Pull request by Lazir**

### CODE REVIEW

**Comment by yajra** [comment]
@Lazir do you have some idea on how I can test/use this PR on my app? I am currently testing Laravel 5.4 and updating my package with dependency on this. Thanks!

**Comment by maddhatter** [comment]
There's also a call in `HtmlServiceProvider` to `getToken()` that needs changed to `token()`. I made the change in my fork, [here](https://github.com/maddhatter/html/commit/8c99401c580c7adcb6f5cacbec4fc1cfb301d652).

**Comment by freekmurze** [comment]
Could you already pull this in (tag is not necessary) so we can use this as a dependency for our packages?

**Comment by maddhatter** [comment]
If you're desperate for something so you can test, I'm using this in my `composer.json`:

```json
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/maddhatter/html.git"
        }
],
"require": {
     "laravelcollective/html": "5.4.x-dev",
}
````

I'll probably go with that until a 5.4 version of this is officially tagged.

**Comment by maddhatter** [comment]
Found another call to `getToken` in `FormBuilder`: https://github.com/maddhatter/html/commit/23223c6e283002f6f092d65015b82d6e3e746206

**Comment by maddhatter** [comment]
What would be the best way to combine the fixes on my fork with this PR?

**Comment by MichalOravec** [comment]
When i update to laravel 5.4 get:
Call to undefined method Illuminate\Foundation\Application::bindShared()

I use yajra/laravel-datatables-oracle and this package required laravelcollective/html

**Comment by laacz** [comment]
As 5.4 is released, this issue starts to become more pressing. Not a big problem for dev environment yet, but it would be nice to know at least some ETA :)

**Comment by mlantz** [comment]
Hey all, sorry I've been swamped lately. I'm going to look over this tonight, and co-ordinate with @adamgoose I'll review the other packages as well

**Comment by JordanDalton** [comment]
Looking forward to this for my 5.4 app

**Comment by OzanKurt** [comment]
:+1:

**Comment by webpatser** [comment]
Every day this takes longer, people will move away from this repo :-( If you don't have time @mlantz please allow another maintainer to test and make it 5.4 ready

**Comment by bbashy** [comment]
Changes have been supplied to you but still pending...?

**Comment by Duka015** [comment]
Still calling `getToken()` in `HtmlServiceProvider`.

**Comment by adamgoose** [comment]
Fixing in #284

**Comment by webfelipemaia** [comment]
I added it to my package.json

```
 require {
        "laravelcollective/html": "~5.0"
}
```
run this

```
composer update
composer dump-autoload -o
```

and it worked

**Pull request merged**
