### PR TITLE
Updates for laravel 5.8

### PR DESCRIPTION
**Pull request by n-osennij**

### CODE REVIEW

**Comment by erayaydin** [comment]
Is there anything for helping you :)

**Comment by nickurt** [comment]
Perfect!, cc @mlantz @decadence

**Comment by codemenorg** [comment]
Please merge it I need it very urgent

**Comment by patrickadvance** [comment]
I need this to be merge, i urgently need this for my project in laravel 5.8

**Comment by kossa** [comment]
We need this :D

**Pull request closed without merging**
