### PR TITLE
Fix getToken() for token().

### PR DESCRIPTION
**Pull request by sroutier**
This was fixed in your 5.4 branch but not in the master branch.
Will need it in master for laravel 5.5 compatibility.
Thanks.
/S

### CODE REVIEW

**Comment by djh101** [comment]
#387 #378 #377 #372

**Comment by dzanfardino** [comment]
Please could someone merge this into master ?

**Comment by huglester** [comment]
maybe something happened to @mlantz ?
He seems to like disappear...

**Comment by decadence** [comment]
Nothing is happened I think.
Just here is no person who can handle this repo timely. These delays are usual thing here.

**Comment by djh101** [comment]
Merged! Hallelujah!

**Pull request merged**
