### PR TITLE
Fix for issue 21

### PR DESCRIPTION
**Pull request by ProjektGopher**

### CODE REVIEW

**Comment by adamgoose** [comment]
Issue #21

**Comment by garygreen** [comment]
Personally I think it's pretty subjective in terms of the output date format. Generally you don't want it to output UTC as the 'human readable' format. I think in this case it's best to avoid model-form binding date values.

**Comment by splatEric** [comment]
Maybe it would be sensible to have a method on FormBuilder where you set date format? or at least allow it to be passed in as an option?

**Comment by splatEric** [comment]
as per my earlier comment, I've made the following commit to a fork from ProjektGopher:

https://github.com/splatEric/html/commit/afb4dc3f653222d8b1dd2c4f4df13fa8470e02c7

If useful, I can do a PR against that fork, and this PR can be updated to include it?

**Comment by karmendra** [comment]
Isn't this about getting the value for a date field when there is a form binding? When I give $value parameter as null for a form binding I expect a value in the form field. I get a value in input attribute but it is not able to put that value in the date field, I get following error.
'The specified value "2015-11-05 00:00:00" does not conform to the required format, "yyyy-MM-dd".'
and I believe that format is a html5 date field requirement.

**Pull request closed without merging**
