### PR TITLE
Clean up formatting

### PR DESCRIPTION
**Pull request by EspadaV8**
There is a lot of messy code that doesn't seem to be following any formatting rules. The files have been run through phpcs, php-cs-fixer and phpcbf as well as a bit of minor checking to make sure that things make sense. There are no code changes in this, but hopefully it'll make future changes easier for people that would be expecting something PSR-1/2.

### CODE REVIEW

**Comment by EspadaV8** [comment]
This is what the PR looks like if you ignore whitespace changes

https://github.com/LaravelCollective/html/pull/131/files?w=1

**Comment by alexandre-butynski** [comment]
I have not reviewed this pull request but the subject should be addressed ! We talk about that since months : #69.

**Comment by aguimaraes** [comment]
+1
Code on 5.1 branch is messy.

**Comment by mlantz** [comment]
Please review conflicts

**Pull request closed without merging**
